/**
 * Quebra-gelos da Val por Área de Atuação
 * 50+ perguntas específicas para cada segmento
 */

export interface Icebreaker {
  id: string
  question: string
  category?: string
}

export const icebreakersByArea: Record<string, Icebreaker[]> = {
  'Designer': [
    { id: 'design-1', question: 'Qual projeto visual te deixou mais orgulhoso esta semana?', category: 'reflexão' },
    { id: 'design-2', question: 'Que tendência de design você está explorando agora?', category: 'aprendizado' },
    { id: 'design-3', question: 'Como você lida com bloqueio criativo?', category: 'desafio' },
    { id: 'design-4', question: 'Qual ferramenta nova descobriu recentemente?', category: 'ferramenta' },
    { id: 'design-5', question: 'Que feedback de cliente mais te surpreendeu?', category: 'cliente' },
    { id: 'design-6', question: 'Qual é sua fonte de inspiração hoje?', category: 'inspiração' },
    { id: 'design-7', question: 'Como você equilibra criatividade e prazo?', category: 'gestão' },
    { id: 'design-8', question: 'Qual designer te inspira atualmente?', category: 'referência' },
    { id: 'design-9', question: 'Que cor te fascina esta semana?', category: 'técnica' },
    { id: 'design-10', question: 'Como você explica suas escolhas criativas?', category: 'apresentação' },
    { id: 'design-11', question: 'Qual seu processo criativo favorito?', category: 'processo' },
    { id: 'design-12', question: 'Como você organiza suas referências visuais?', category: 'organização' },
    { id: 'design-13', question: 'Qual projeto gostaria de ter feito?', category: 'aspiração' },
    { id: 'design-14', question: 'Como você lida com revisões infinitas?', category: 'desafio' },
    { id: 'design-15', question: 'Qual tipografia você está usando muito?', category: 'técnica' },
    { id: 'design-16', question: 'Como você apresenta conceitos para clientes?', category: 'apresentação' },
    { id: 'design-17', question: 'Qual atalho do Photoshop você mais usa?', category: 'produtividade' },
    { id: 'design-18', question: 'Como você escolhe paletas de cores?', category: 'técnica' },
    { id: 'design-19', question: 'Qual marca tem o melhor design na sua opinião?', category: 'referência' },
    { id: 'design-20', question: 'Como você documenta seu processo criativo?', category: 'processo' },
    { id: 'design-21', question: 'Qual elemento visual você adora usar?', category: 'estilo' },
    { id: 'design-22', question: 'Como você se mantém atualizado?', category: 'aprendizado' },
    { id: 'design-23', question: 'Qual crítica construtiva te ajudou mais?', category: 'crescimento' },
    { id: 'design-24', question: 'Como você cria identidades memoráveis?', category: 'branding' },
    { id: 'design-25', question: 'Qual seu estilo de design favorito?', category: 'estilo' },
    { id: 'design-26', question: 'Como você lida com briefs vagos?', category: 'desafio' },
    { id: 'design-27', question: 'Qual plugin/extensão é indispensável?', category: 'ferramenta' },
    { id: 'design-28', question: 'Como você valida suas ideias?', category: 'processo' },
    { id: 'design-29', question: 'Qual composição visual te impressionou?', category: 'inspiração' },
    { id: 'design-30', question: 'Como você gerencia múltiplos projetos?', category: 'gestão' },
    { id: 'design-31', question: 'Qual princípio de design você prioriza?', category: 'fundamento' },
    { id: 'design-32', question: 'Como você cria hierarquia visual?', category: 'técnica' },
    { id: 'design-33', question: 'Qual recurso gratuito você recomenda?', category: 'recurso' },
    { id: 'design-34', question: 'Como você se recupera de um projeto difícil?', category: 'resiliência' },
    { id: 'design-35', question: 'Qual tendência você ignora de propósito?', category: 'opinião' },
    { id: 'design-36', question: 'Como você vende sua ideia favorita?', category: 'persuasão' },
    { id: 'design-37', question: 'Qual detalhe faz diferença nos seus designs?', category: 'detalhe' },
    { id: 'design-38', question: 'Como você colabora com outros designers?', category: 'colaboração' },
    { id: 'design-39', question: 'Qual erro te ensinou mais?', category: 'aprendizado' },
    { id: 'design-40', question: 'Como você define seu estilo pessoal?', category: 'identidade' },
    { id: 'design-41', question: 'Qual conferência/evento te marcou?', category: 'networking' },
    { id: 'design-42', question: 'Como você precifica seu trabalho?', category: 'negócio' },
    { id: 'design-43', question: 'Qual software você domina melhor?', category: 'expertise' },
    { id: 'design-44', question: 'Como você lida com cópias de referência?', category: 'ética' },
    { id: 'design-45', question: 'Qual aspecto do design quer melhorar?', category: 'desenvolvimento' },
    { id: 'design-46', question: 'Como você mantém consistência visual?', category: 'qualidade' },
    { id: 'design-47', question: 'Qual projeto te tirou da zona de conforto?', category: 'crescimento' },
    { id: 'design-48', question: 'Como você celebra conquistas criativas?', category: 'motivação' },
    { id: 'design-49', question: 'Qual conselho daria ao você de 5 anos atrás?', category: 'sabedoria' },
    { id: 'design-50', question: 'Como você equilibra originalidade e funcionalidade?', category: 'filosofia' }
  ],

  'Design Gráfico': [
    { id: 'dg-1', question: 'Qual projeto visual te deixou mais orgulhoso esta semana?', category: 'reflexão' },
    { id: 'dg-2', question: 'Que tendência de design você está explorando agora?', category: 'aprendizado' },
    { id: 'dg-3', question: 'Como você lida com bloqueio criativo?', category: 'desafio' },
    { id: 'dg-4', question: 'Qual ferramenta nova descobriu recentemente?', category: 'ferramenta' },
    { id: 'dg-5', question: 'Que feedback de cliente mais te surpreendeu?', category: 'cliente' },
    { id: 'dg-6', question: 'Qual é sua fonte de inspiração hoje?', category: 'inspiração' },
    { id: 'dg-7', question: 'Como você equilibra criatividade e prazo?', category: 'gestão' },
    { id: 'dg-8', question: 'Qual designer te inspira atualmente?', category: 'referência' },
    { id: 'dg-9', question: 'Que cor te fascina esta semana?', category: 'técnica' },
    { id: 'dg-10', question: 'Como você explica suas escolhas criativas?', category: 'apresentação' },
    { id: 'dg-11', question: 'Qual seu processo criativo favorito?', category: 'processo' },
    { id: 'dg-12', question: 'Como você organiza suas referências visuais?', category: 'organização' },
    { id: 'dg-13', question: 'Qual projeto gostaria de ter feito?', category: 'aspiração' },
    { id: 'dg-14', question: 'Como você lida com revisões infinitas?', category: 'desafio' },
    { id: 'dg-15', question: 'Qual tipografia você está usando muito?', category: 'técnica' },
    { id: 'dg-16', question: 'Como você apresenta conceitos para clientes?', category: 'apresentação' },
    { id: 'dg-17', question: 'Qual atalho do Illustrator você mais usa?', category: 'produtividade' },
    { id: 'dg-18', question: 'Como você escolhe paletas de cores?', category: 'técnica' },
    { id: 'dg-19', question: 'Qual marca tem o melhor design na sua opinião?', category: 'referência' },
    { id: 'dg-20', question: 'Como você documenta seu processo criativo?', category: 'processo' },
    { id: 'dg-21', question: 'Qual elemento visual você adora usar?', category: 'estilo' },
    { id: 'dg-22', question: 'Como você se mantém atualizado?', category: 'aprendizado' },
    { id: 'dg-23', question: 'Qual crítica construtiva te ajudou mais?', category: 'crescimento' },
    { id: 'dg-24', question: 'Como você cria identidades memoráveis?', category: 'branding' },
    { id: 'dg-25', question: 'Qual seu estilo de design favorito?', category: 'estilo' },
    { id: 'dg-26', question: 'Como você lida com briefs vagos?', category: 'desafio' },
    { id: 'dg-27', question: 'Qual plugin/extensão é indispensável?', category: 'ferramenta' },
    { id: 'dg-28', question: 'Como você valida suas ideias?', category: 'processo' },
    { id: 'dg-29', question: 'Qual composição visual te impressionou?', category: 'inspiração' },
    { id: 'dg-30', question: 'Como você gerencia múltiplos projetos?', category: 'gestão' },
    { id: 'dg-31', question: 'Qual princípio de design você prioriza?', category: 'fundamento' },
    { id: 'dg-32', question: 'Como você cria hierarquia visual?', category: 'técnica' },
    { id: 'dg-33', question: 'Qual recurso gratuito você recomenda?', category: 'recurso' },
    { id: 'dg-34', question: 'Como você se recupera de um projeto difícil?', category: 'resiliência' },
    { id: 'dg-35', question: 'Qual tendência você ignora de propósito?', category: 'opinião' },
    { id: 'dg-36', question: 'Como você vende sua ideia favorita?', category: 'persuasão' },
    { id: 'dg-37', question: 'Qual detalhe faz diferença nos seus designs?', category: 'detalhe' },
    { id: 'dg-38', question: 'Como você colabora com outros designers?', category: 'colaboração' },
    { id: 'dg-39', question: 'Qual erro te ensinou mais?', category: 'aprendizado' },
    { id: 'dg-40', question: 'Como você define seu estilo pessoal?', category: 'identidade' },
    { id: 'dg-41', question: 'Qual conferência/evento te marcou?', category: 'networking' },
    { id: 'dg-42', question: 'Como você precifica seu trabalho?', category: 'negócio' },
    { id: 'dg-43', question: 'Qual software você domina melhor?', category: 'expertise' },
    { id: 'dg-44', question: 'Como você lida com cópias de referência?', category: 'ética' },
    { id: 'dg-45', question: 'Qual aspecto do design quer melhorar?', category: 'desenvolvimento' },
    { id: 'dg-46', question: 'Como você mantém consistência visual?', category: 'qualidade' },
    { id: 'dg-47', question: 'Qual projeto te tirou da zona de conforto?', category: 'crescimento' },
    { id: 'dg-48', question: 'Como você celebra conquistas criativas?', category: 'motivação' },
    { id: 'dg-49', question: 'Qual conselho daria ao você de 5 anos atrás?', category: 'sabedoria' },
    { id: 'dg-50', question: 'Como você equilibra originalidade e funcionalidade?', category: 'filosofia' }
  ],

  'Web Designer': [
    { id: 'web-1', question: 'Qual desafio de UX você resolveu recentemente?', category: 'solução' },
    { id: 'web-2', question: 'Como você testa usabilidade dos seus projetos?', category: 'qualidade' },
    { id: 'web-3', question: 'Qual biblioteca/framework está te animando?', category: 'tecnologia' },
    { id: 'web-4', question: 'Como equilibra estética e performance?', category: 'balance' },
    { id: 'web-5', question: 'Qual princípio de acessibilidade aplica mais?', category: 'inclusão' },
    { id: 'web-6', question: 'Como você pensa mobile-first?', category: 'abordagem' },
    { id: 'web-7', question: 'Qual animação CSS te impressionou?', category: 'técnica' },
    { id: 'web-8', question: 'Como você lida com navegadores antigos?', category: 'compatibilidade' },
    { id: 'web-9', question: 'Qual métrica de performance monitora mais?', category: 'otimização' },
    { id: 'web-10', question: 'Como você documenta seu código?', category: 'documentação' },
    { id: 'web-11', question: 'Qual design system te inspira?', category: 'referência' },
    { id: 'web-12', question: 'Como você estrutura componentes reutilizáveis?', category: 'arquitetura' },
    { id: 'web-13', question: 'Qual ferramenta de prototipagem prefere?', category: 'ferramenta' },
    { id: 'web-14', question: 'Como você garante acessibilidade?', category: 'wcag' },
    { id: 'web-15', question: 'Qual padrão de UI você usa frequentemente?', category: 'padrão' },
    { id: 'web-16', question: 'Como você otimiza imagens para web?', category: 'performance' },
    { id: 'web-17', question: 'Qual microinteração você adora?', category: 'detalhe' },
    { id: 'web-18', question: 'Como você estrutura breakpoints?', category: 'responsivo' },
    { id: 'web-19', question: 'Qual website tem melhor UX na sua opinião?', category: 'referência' },
    { id: 'web-20', question: 'Como você lida com dark mode?', category: 'tema' },
    { id: 'web-21', question: 'Qual biblioteca de componentes usa?', category: 'biblioteca' },
    { id: 'web-22', question: 'Como você valida suas decisões de UX?', category: 'validação' },
    { id: 'web-23', question: 'Qual aspecto de CSS você domina?', category: 'expertise' },
    { id: 'web-24', question: 'Como você organiza seus estilos?', category: 'organização' },
    { id: 'web-25', question: 'Qual estratégia de loading você prefere?', category: 'performance' },
    { id: 'web-26', question: 'Como você trata estados de erro?', category: 'ux' },
    { id: 'web-27', question: 'Qual plugin do Figma é essencial?', category: 'ferramenta' },
    { id: 'web-28', question: 'Como você colabora com desenvolvedores?', category: 'colaboração' },
    { id: 'web-29', question: 'Qual princípio de design prioriza?', category: 'fundamento' },
    { id: 'web-30', question: 'Como você conduz testes de usabilidade?', category: 'pesquisa' },
    { id: 'web-31', question: 'Qual ferramenta de analytics usa?', category: 'dados' },
    { id: 'web-32', question: 'Como você decide hierarquia visual?', category: 'design' },
    { id: 'web-33', question: 'Qual técnica de SEO aplica no design?', category: 'seo' },
    { id: 'web-34', question: 'Como você mantém consistência?', category: 'qualidade' },
    { id: 'web-35', question: 'Qual recurso de CSS moderno adora?', category: 'tecnologia' },
    { id: 'web-36', question: 'Como você lida com feedback conflitante?', category: 'gestão' },
    { id: 'web-37', question: 'Qual website você refez mentalmente?', category: 'crítica' },
    { id: 'web-38', question: 'Como você aprende novas tecnologias?', category: 'aprendizado' },
    { id: 'web-39', question: 'Qual erro de UX você evita sempre?', category: 'experiência' },
    { id: 'web-40', question: 'Como você mede sucesso de um design?', category: 'métrica' },
    { id: 'web-41', question: 'Qual tendência de web design você segue?', category: 'trend' },
    { id: 'web-42', question: 'Como você documenta padrões de UI?', category: 'documentação' },
    { id: 'web-43', question: 'Qual aspecto de UX quer aprofundar?', category: 'desenvolvimento' },
    { id: 'web-44', question: 'Como você prioriza features de interface?', category: 'estratégia' },
    { id: 'web-45', question: 'Qual framework CSS prefere e por quê?', category: 'opinião' },
    { id: 'web-46', question: 'Como você lida com requests de última hora?', category: 'pressão' },
    { id: 'web-47', question: 'Qual projeto web te orgulha mais?', category: 'conquista' },
    { id: 'web-48', question: 'Como você mantém designs acessíveis?', category: 'inclusão' },
    { id: 'web-49', question: 'Qual conselho daria a novos web designers?', category: 'mentoria' },
    { id: 'web-50', question: 'Como você equilibra criatividade e usabilidade?', category: 'filosofia' }
  ],

  'Videomaker': [
    { id: 'video-1', question: 'Qual técnica de edição aprendeu esta semana?', category: 'aprendizado' },
    { id: 'video-2', question: 'Como você conta histórias através de vídeos?', category: 'storytelling' },
    { id: 'video-3', question: 'Qual projeto de motion graphics te inspirou?', category: 'inspiração' },
    { id: 'video-4', question: 'Como você lida com prazos apertados?', category: 'pressão' },
    { id: 'video-5', question: 'Qual transição criativa você descobriu?', category: 'técnica' },
    { id: 'video-6', question: 'Como você escolhe trilha sonora?', category: 'áudio' },
    { id: 'video-7', question: 'Qual efeito visual dominou recentemente?', category: 'skill' },
    { id: 'video-8', question: 'Como você estrutura narrativa de vídeo?', category: 'roteiro' },
    { id: 'video-9', question: 'Qual canal/creator te inspira?', category: 'referência' },
    { id: 'video-10', question: 'Como você otimiza renderização?', category: 'workflow' },
    { id: 'video-11', question: 'Qual plugin do Premiere é essencial?', category: 'ferramenta' },
    { id: 'video-12', question: 'Como você faz color grading?', category: 'pós-produção' },
    { id: 'video-13', question: 'Qual tipo de vídeo prefere criar?', category: 'preferência' },
    { id: 'video-14', question: 'Como você capta áudio de qualidade?', category: 'captação' },
    { id: 'video-15', question: 'Qual software de edição domina?', category: 'expertise' },
    { id: 'video-16', question: 'Como você cria ritmo no vídeo?', category: 'edição' },
    { id: 'video-17', question: 'Qual projeto teve melhor resultado?', category: 'sucesso' },
    { id: 'video-18', question: 'Como você organiza seus arquivos?', category: 'organização' },
    { id: 'video-19', question: 'Qual aspecto técnico quer melhorar?', category: 'desenvolvimento' },
    { id: 'video-20', question: 'Como você equilibra qualidade e deadline?', category: 'gestão' },
    { id: 'video-21', question: 'Qual câmera/equipamento você recomenda?', category: 'equipamento' },
    { id: 'video-22', question: 'Como você planeja suas gravações?', category: 'planejamento' },
    { id: 'video-23', question: 'Qual erro de edição você evita?', category: 'qualidade' },
    { id: 'video-24', question: 'Como você cria thumbnails atrativas?', category: 'marketing' },
    { id: 'video-25', question: 'Qual formato de vídeo está em alta?', category: 'trend' },
    { id: 'video-26', question: 'Como você trabalha com clientes?', category: 'relacionamento' },
    { id: 'video-27', question: 'Qual iluminação você prefere?', category: 'técnica' },
    { id: 'video-28', question: 'Como você mantém consistência visual?', category: 'branding' },
    { id: 'video-29', question: 'Qual transição você usa demais?', category: 'estilo' },
    { id: 'video-30', question: 'Como você sincroniza áudio e vídeo?', category: 'técnica' },
    { id: 'video-31', question: 'Qual projeto te tirou da zona de conforto?', category: 'desafio' },
    { id: 'video-32', question: 'Como você cria legendas eficientes?', category: 'acessibilidade' },
    { id: 'video-33', question: 'Qual banco de música você usa?', category: 'recurso' },
    { id: 'video-34', question: 'Como você lida com feedback negativo?', category: 'resiliência' },
    { id: 'video-35', question: 'Qual storytelling te emocionou?', category: 'inspiração' },
    { id: 'video-36', question: 'Como você otimiza para cada plataforma?', category: 'distribuição' },
    { id: 'video-37', question: 'Qual atalho do After Effects você ama?', category: 'produtividade' },
    { id: 'video-38', question: 'Como você precifica seus vídeos?', category: 'negócio' },
    { id: 'video-39', question: 'Qual tendência de vídeo você segue?', category: 'mercado' },
    { id: 'video-40', question: 'Como você mantém criatividade alta?', category: 'inspiração' },
    { id: 'video-41', question: 'Qual codec você exporta seus vídeos?', category: 'técnica' },
    { id: 'video-42', question: 'Como você faz backup dos projetos?', category: 'segurança' },
    { id: 'video-43', question: 'Qual animação você criou recentemente?', category: 'motion' },
    { id: 'video-44', question: 'Como você colabora com outros criativos?', category: 'equipe' },
    { id: 'video-45', question: 'Qual vídeo viral você analisou?', category: 'estudo' },
    { id: 'video-46', question: 'Como você melhora retenção de audiência?', category: 'engajamento' },
    { id: 'video-47', question: 'Qual técnica de composição você usa?', category: 'cinematografia' },
    { id: 'video-48', question: 'Como você adiciona personalidade aos vídeos?', category: 'estilo' },
    { id: 'video-49', question: 'Qual conselho daria a novos videomakers?', category: 'mentoria' },
    { id: 'video-50', question: 'Como você define sucesso de um vídeo?', category: 'métrica' }
  ],

  'Head de Marketing': [
    { id: 'head-1', question: 'Qual métrica está sendo seu maior desafio?', category: 'kpi' },
    { id: 'head-2', question: 'Como você desenvolve sua equipe?', category: 'liderança' },
    { id: 'head-3', question: 'Que estratégia nova está testando?', category: 'inovação' },
    { id: 'head-4', question: 'Como mede sucesso das campanhas?', category: 'analytics' },
    { id: 'head-5', question: 'Como você alinha marketing e vendas?', category: 'sinergia' },
    { id: 'head-6', question: 'Qual decisão estratégica tomou hoje?', category: 'estratégia' },
    { id: 'head-7', question: 'Como você prioriza projetos?', category: 'gestão' },
    { id: 'head-8', question: 'Qual insight de dados te surpreendeu?', category: 'analytics' },
    { id: 'head-9', question: 'Como você motiva sua equipe?', category: 'liderança' },
    { id: 'head-10', question: 'Qual tendência de mercado está observando?', category: 'mercado' },
    { id: 'head-11', question: 'Como você distribui budget entre canais?', category: 'orçamento' },
    { id: 'head-12', question: 'Qual campanha teve melhor ROI?', category: 'resultado' },
    { id: 'head-13', question: 'Como você lida com pressão por resultados?', category: 'pressão' },
    { id: 'head-14', question: 'Qual estratégia de conteúdo funciona?', category: 'conteúdo' },
    { id: 'head-15', question: 'Como você define personas?', category: 'targeting' },
    { id: 'head-16', question: 'Qual ferramenta de automação usa?', category: 'tecnologia' },
    { id: 'head-17', question: 'Como você apresenta resultados?', category: 'comunicação' },
    { id: 'head-18', question: 'Qual erro de marketing você evita?', category: 'aprendizado' },
    { id: 'head-19', question: 'Como você testa novas ideias?', category: 'experimentação' },
    { id: 'head-20', question: 'Qual marca inspira sua estratégia?', category: 'referência' },
    { id: 'head-21', question: 'Como você gerencia stakeholders?', category: 'política' },
    { id: 'head-22', question: 'Qual KPI você nunca ignora?', category: 'métrica' },
    { id: 'head-23', question: 'Como você equilibra curto e longo prazo?', category: 'planejamento' },
    { id: 'head-24', question: 'Qual canal traz melhores leads?', category: 'aquisição' },
    { id: 'head-25', question: 'Como você cria cultura data-driven?', category: 'cultura' },
    { id: 'head-26', question: 'Qual decisão difícil tomou recentemente?', category: 'liderança' },
    { id: 'head-27', question: 'Como você identifica oportunidades?', category: 'visão' },
    { id: 'head-28', question: 'Qual framework de marketing usa?', category: 'metodologia' },
    { id: 'head-29', question: 'Como você retém clientes?', category: 'retenção' },
    { id: 'head-30', question: 'Qual aprendizado marcou sua carreira?', category: 'experiência' },
    { id: 'head-31', question: 'Como você escala estratégias que funcionam?', category: 'crescimento' },
    { id: 'head-32', question: 'Qual processo você automatizou?', category: 'eficiência' },
    { id: 'head-33', question: 'Como você lida com orçamento limitado?', category: 'criatividade' },
    { id: 'head-34', question: 'Qual competidor você admira?', category: 'benchmarking' },
    { id: 'head-35', question: 'Como você desenvolve posicionamento único?', category: 'branding' },
    { id: 'head-36', question: 'Qual mudança de mercado te preocupa?', category: 'tendência' },
    { id: 'head-37', question: 'Como você mede brand awareness?', category: 'marca' },
    { id: 'head-38', question: 'Qual talento você busca na equipe?', category: 'recrutamento' },
    { id: 'head-39', question: 'Como você valida novas estratégias?', category: 'teste' },
    { id: 'head-40', question: 'Qual livro/podcast mudou sua visão?', category: 'aprendizado' },
    { id: 'head-41', question: 'Como você lida com falhas de campanha?', category: 'resiliência' },
    { id: 'head-42', question: 'Qual métrica considera overrated?', category: 'opinião' },
    { id: 'head-43', question: 'Como você constrói autoridade de marca?', category: 'thought-leadership' },
    { id: 'head-44', question: 'Qual decisão te tirou da zona de conforto?', category: 'coragem' },
    { id: 'head-45', question: 'Como você equilibra inovação e resultado?', category: 'balance' },
    { id: 'head-46', question: 'Qual parceria estratégica funcionou?', category: 'networking' },
    { id: 'head-47', question: 'Como você prepara sua equipe para o futuro?', category: 'desenvolvimento' },
    { id: 'head-48', question: 'Qual conselho daria a novos heads?', category: 'mentoria' },
    { id: 'head-49', question: 'Como você define sucesso em marketing?', category: 'filosofia' },
    { id: 'head-50', question: 'Qual legado quer deixar na área?', category: 'propósito' }
  ],

  'Head Marketing': [
    { id: 'headm-1', question: 'Qual métrica está sendo seu maior desafio?', category: 'kpi' },
    { id: 'headm-2', question: 'Como você desenvolve sua equipe?', category: 'liderança' },
    { id: 'headm-3', question: 'Que estratégia nova está testando?', category: 'inovação' },
    { id: 'headm-4', question: 'Como mede sucesso das campanhas?', category: 'analytics' },
    { id: 'headm-5', question: 'Como você alinha marketing e vendas?', category: 'sinergia' },
    { id: 'headm-6', question: 'Qual decisão estratégica tomou hoje?', category: 'estratégia' },
    { id: 'headm-7', question: 'Como você prioriza projetos?', category: 'gestão' },
    { id: 'headm-8', question: 'Qual insight de dados te surpreendeu?', category: 'analytics' },
    { id: 'headm-9', question: 'Como você motiva sua equipe?', category: 'liderança' },
    { id: 'headm-10', question: 'Qual tendência de mercado está observando?', category: 'mercado' },
    { id: 'headm-11', question: 'Como você distribui budget entre canais?', category: 'orçamento' },
    { id: 'headm-12', question: 'Qual campanha teve melhor ROI?', category: 'resultado' },
    { id: 'headm-13', question: 'Como você lida com pressão por resultados?', category: 'pressão' },
    { id: 'headm-14', question: 'Qual estratégia de conteúdo funciona?', category: 'conteúdo' },
    { id: 'headm-15', question: 'Como você define personas?', category: 'targeting' },
    { id: 'headm-16', question: 'Qual ferramenta de automação usa?', category: 'tecnologia' },
    { id: 'headm-17', question: 'Como você apresenta resultados?', category: 'comunicação' },
    { id: 'headm-18', question: 'Qual erro de marketing você evita?', category: 'aprendizado' },
    { id: 'headm-19', question: 'Como você testa novas ideias?', category: 'experimentação' },
    { id: 'headm-20', question: 'Qual marca inspira sua estratégia?', category: 'referência' },
    { id: 'headm-21', question: 'Como você gerencia stakeholders?', category: 'política' },
    { id: 'headm-22', question: 'Qual KPI você nunca ignora?', category: 'métrica' },
    { id: 'headm-23', question: 'Como você equilibra curto e longo prazo?', category: 'planejamento' },
    { id: 'headm-24', question: 'Qual canal traz melhores leads?', category: 'aquisição' },
    { id: 'headm-25', question: 'Como você cria cultura data-driven?', category: 'cultura' },
    { id: 'headm-26', question: 'Qual decisão difícil tomou recentemente?', category: 'liderança' },
    { id: 'headm-27', question: 'Como você identifica oportunidades?', category: 'visão' },
    { id: 'headm-28', question: 'Qual framework de marketing usa?', category: 'metodologia' },
    { id: 'headm-29', question: 'Como você retém clientes?', category: 'retenção' },
    { id: 'headm-30', question: 'Qual aprendizado marcou sua carreira?', category: 'experiência' },
    { id: 'headm-31', question: 'Como você escala estratégias que funcionam?', category: 'crescimento' },
    { id: 'headm-32', question: 'Qual processo você automatizou?', category: 'eficiência' },
    { id: 'headm-33', question: 'Como você lida com orçamento limitado?', category: 'criatividade' },
    { id: 'headm-34', question: 'Qual competidor você admira?', category: 'benchmarking' },
    { id: 'headm-35', question: 'Como você desenvolve posicionamento único?', category: 'branding' },
    { id: 'headm-36', question: 'Qual mudança de mercado te preocupa?', category: 'tendência' },
    { id: 'headm-37', question: 'Como você mede brand awareness?', category: 'marca' },
    { id: 'headm-38', question: 'Qual talento você busca na equipe?', category: 'recrutamento' },
    { id: 'headm-39', question: 'Como você valida novas estratégias?', category: 'teste' },
    { id: 'headm-40', question: 'Qual livro/podcast mudou sua visão?', category: 'aprendizado' },
    { id: 'headm-41', question: 'Como você lida com falhas de campanha?', category: 'resiliência' },
    { id: 'headm-42', question: 'Qual métrica considera overrated?', category: 'opinião' },
    { id: 'headm-43', question: 'Como você constrói autoridade de marca?', category: 'thought-leadership' },
    { id: 'headm-44', question: 'Qual decisão te tirou da zona de conforto?', category: 'coragem' },
    { id: 'headm-45', question: 'Como você equilibra inovação e resultado?', category: 'balance' },
    { id: 'headm-46', question: 'Qual parceria estratégica funcionou?', category: 'networking' },
    { id: 'headm-47', question: 'Como você prepara sua equipe para o futuro?', category: 'desenvolvimento' },
    { id: 'headm-48', question: 'Qual conselho daria a novos heads?', category: 'mentoria' },
    { id: 'headm-49', question: 'Como você define sucesso em marketing?', category: 'filosofia' },
    { id: 'headm-50', question: 'Qual legado quer deixar na área?', category: 'propósito' }
  ],

  'Tráfego Pago': [
    { id: 'trafego-1', question: 'Qual campanha superou suas expectativas?', category: 'sucesso' },
    { id: 'trafego-2', question: 'Como você otimiza orçamentos apertados?', category: 'otimização' },
    { id: 'trafego-3', question: 'Que teste A/B te surpreendeu?', category: 'teste' },
    { id: 'trafego-4', question: 'Como você lida com CPCs altos?', category: 'desafio' },
    { id: 'trafego-5', question: 'Qual segmentação funcionou melhor?', category: 'targeting' },
    { id: 'trafego-6', question: 'Como você analisa concorrentes?', category: 'análise' },
    { id: 'trafego-7', question: 'Qual plataforma está performando mais?', category: 'canal' },
    { id: 'trafego-8', question: 'Como você estrutura suas campanhas?', category: 'estrutura' },
    { id: 'trafego-9', question: 'Qual métrica acompanha mais de perto?', category: 'kpi' },
    { id: 'trafego-10', question: 'Como você explica resultados para clientes?', category: 'comunicação' },
    { id: 'trafego-11', question: 'Qual erro de campanha você evita?', category: 'aprendizado' },
    { id: 'trafego-12', question: 'Como você define lances otimizados?', category: 'estratégia' },
    { id: 'trafego-13', question: 'Qual criativo teve melhor CTR?', category: 'criativos' },
    { id: 'trafego-14', question: 'Como você escala campanhas lucrativas?', category: 'escala' },
    { id: 'trafego-15', question: 'Qual ferramenta de análise prefere?', category: 'ferramenta' },
    { id: 'trafego-16', question: 'Como você testa novas plataformas?', category: 'inovação' },
    { id: 'trafego-17', question: 'Qual público te surpreendeu positivamente?', category: 'audiência' },
    { id: 'trafego-18', question: 'Como você lida com sazonalidade?', category: 'planejamento' },
    { id: 'trafego-19', question: 'Qual estratégia de remarketing usa?', category: 'remarketing' },
    { id: 'trafego-20', question: 'Como você otimiza landing pages?', category: 'conversão' },
    { id: 'trafego-21', question: 'Qual mudança de algoritmo te afetou?', category: 'adaptação' },
    { id: 'trafego-22', question: 'Como você distribui budget entre campanhas?', category: 'budget' },
    { id: 'trafego-23', question: 'Qual copy gerou mais conversões?', category: 'copywriting' },
    { id: 'trafego-24', question: 'Como você identifica fraudes de clique?', category: 'qualidade' },
    { id: 'trafego-25', question: 'Qual horário performa melhor?', category: 'timing' },
    { id: 'trafego-26', question: 'Como você qualifica leads de anúncios?', category: 'qualificação' },
    { id: 'trafego-27', question: 'Qual extensão de anúncio funciona?', category: 'recurso' },
    { id: 'trafego-28', question: 'Como você recupera carrinhos abandonados?', category: 'e-commerce' },
    { id: 'trafego-29', question: 'Qual métrica ignora de propósito?', category: 'foco' },
    { id: 'trafego-30', question: 'Como você treina novos gestores?', category: 'mentoria' },
    { id: 'trafego-31', question: 'Qual campanha foi seu maior aprendizado?', category: 'experiência' },
    { id: 'trafego-32', question: 'Como você lida com rejeições de anúncio?', category: 'compliance' },
    { id: 'trafego-33', question: 'Qual objetivo de campanha prioriza?', category: 'objetivo' },
    { id: 'trafego-34', question: 'Como você testa criativos rapidamente?', category: 'agilidade' },
    { id: 'trafego-35', question: 'Qual dia da semana converte mais?', category: 'timing' },
    { id: 'trafego-36', question: 'Como você justifica investimento em topo de funil?', category: 'estratégia' },
    { id: 'trafego-37', question: 'Qual ferramenta de automação usa?', category: 'automação' },
    { id: 'trafego-38', question: 'Como você lida com fadiga de anúncio?', category: 'refresh' },
    { id: 'trafego-39', question: 'Qual lookalike audience funcionou?', category: 'segmentação' },
    { id: 'trafego-40', question: 'Como você mede incrementalidade?', category: 'mensuração' },
    { id: 'trafego-41', question: 'Qual formato de anúncio prefere?', category: 'formato' },
    { id: 'trafego-42', question: 'Como você negocia com plataformas?', category: 'relacionamento' },
    { id: 'trafego-43', question: 'Qual tendência de mídia paga você acompanha?', category: 'trend' },
    { id: 'trafego-44', question: 'Como você documenta seus testes?', category: 'organização' },
    { id: 'trafego-45', question: 'Qual erro custou mais caro?', category: 'lição' },
    { id: 'trafego-46', question: 'Como você equilibra brand e performance?', category: 'balance' },
    { id: 'trafego-47', question: 'Qual certificação recomenda?', category: 'educação' },
    { id: 'trafego-48', question: 'Como você prevê resultados futuros?', category: 'previsão' },
    { id: 'trafego-49', question: 'Qual conselho daria a iniciantes?', category: 'mentoria' },
    { id: 'trafego-50', question: 'Como você define ROI aceitável?', category: 'métrica' }
  ],

  'Social Media': [
    { id: 'social-1', question: 'Qual conteúdo gerou mais engajamento?', category: 'sucesso' },
    { id: 'social-2', question: 'Como você se mantém atualizado com algoritmos?', category: 'aprendizado' },
    { id: 'social-3', question: 'Que tipo de post funciona melhor?', category: 'formato' },
    { id: 'social-4', question: 'Como você lida com crises nas redes?', category: 'gestão' },
    { id: 'social-5', question: 'Qual trend você surfou recentemente?', category: 'trend' },
    { id: 'social-6', question: 'Como você planeja seu calendário editorial?', category: 'planejamento' },
    { id: 'social-7', question: 'Qual rede social está crescendo mais?', category: 'plataforma' },
    { id: 'social-8', question: 'Como você mede sentimento da audiência?', category: 'analytics' },
    { id: 'social-9', question: 'Qual formato de conteúdo testa mais?', category: 'experimentação' },
    { id: 'social-10', question: 'Como você engaja comunidade?', category: 'community' },
    { id: 'social-11', question: 'Qual horário de postagem funciona?', category: 'timing' },
    { id: 'social-12', question: 'Como você cria legendas envolventes?', category: 'copywriting' },
    { id: 'social-13', question: 'Qual ferramenta de agendamento usa?', category: 'ferramenta' },
    { id: 'social-14', question: 'Como você lida com comentários negativos?', category: 'gestão' },
    { id: 'social-15', question: 'Qual métrica você prioriza?', category: 'kpi' },
    { id: 'social-16', question: 'Como você identifica micro-influenciadores?', category: 'parcerias' },
    { id: 'social-17', question: 'Qual conteúdo user-generated funcionou?', category: 'ugc' },
    { id: 'social-18', question: 'Como você adapta conteúdo por plataforma?', category: 'estratégia' },
    { id: 'social-19', question: 'Qual hashtag strategy você usa?', category: 'alcance' },
    { id: 'social-20', question: 'Como você mede ROI de social media?', category: 'mensuração' },
    { id: 'social-21', question: 'Qual post você gostaria de deletar?', category: 'aprendizado' },
    { id: 'social-22', question: 'Como você cria stories envolventes?', category: 'stories' },
    { id: 'social-23', question: 'Qual live teve mais impacto?', category: 'live' },
    { id: 'social-24', question: 'Como você constrói autoridade na marca?', category: 'branding' },
    { id: 'social-25', question: 'Qual erro de principiante você evita?', category: 'experiência' },
    { id: 'social-26', question: 'Como você lida com trolls?', category: 'gestão' },
    { id: 'social-27', question: 'Qual tipo de reel performa melhor?', category: 'reels' },
    { id: 'social-28', question: 'Como você valida ideias de conteúdo?', category: 'teste' },
    { id: 'social-29', question: 'Qual partnership com creator funcionou?', category: 'influencer' },
    { id: 'social-30', question: 'Como você cresce seguidores organicamente?', category: 'crescimento' },
    { id: 'social-31', question: 'Qual ferramenta de design usa?', category: 'criação' },
    { id: 'social-32', question: 'Como você equilibra promoção e valor?', category: 'conteúdo' },
    { id: 'social-33', question: 'Qual trend você ignora de propósito?', category: 'estratégia' },
    { id: 'social-34', question: 'Como você reporta resultados?', category: 'comunicação' },
    { id: 'social-35', question: 'Qual campanha viral você estudou?', category: 'estudo' },
    { id: 'social-36', question: 'Como você gerencia múltiplas contas?', category: 'produtividade' },
    { id: 'social-37', question: 'Qual tipo de enquete engaja mais?', category: 'interação' },
    { id: 'social-38', question: 'Como você mede brand awareness?', category: 'marca' },
    { id: 'social-39', question: 'Qual formato de carrossel funciona?', category: 'formato' },
    { id: 'social-40', question: 'Como você lida com mudanças de algoritmo?', category: 'adaptação' },
    { id: 'social-41', question: 'Qual audio trending você usou?', category: 'audio' },
    { id: 'social-42', question: 'Como você cria senso de urgência?', category: 'conversão' },
    { id: 'social-43', question: 'Qual marca você admira nas redes?', category: 'benchmarking' },
    { id: 'social-44', question: 'Como você evita burnout criativo?', category: 'wellbeing' },
    { id: 'social-45', question: 'Qual métrica de engajamento monitora?', category: 'analytics' },
    { id: 'social-46', question: 'Como você transforma seguidores em clientes?', category: 'conversão' },
    { id: 'social-47', question: 'Qual tipo de CTA funciona melhor?', category: 'call-to-action' },
    { id: 'social-48', question: 'Como você mantém consistência visual?', category: 'branding' },
    { id: 'social-49', question: 'Qual conselho daria a novos SMMs?', category: 'mentoria' },
    { id: 'social-50', question: 'Como você define sucesso em social?', category: 'objetivo' }
  ],

  'Comercial': [
    { id: 'comercial-1', question: 'Como superou a última objeção difícil?', category: 'técnica' },
    { id: 'comercial-2', question: 'Qual técnica de negociação está funcionando?', category: 'negociação' },
    { id: 'comercial-3', question: 'Como você qualifica seus leads?', category: 'qualificação' },
    { id: 'comercial-4', question: 'Qual foi sua melhor venda da semana?', category: 'conquista' },
    { id: 'comercial-5', question: 'Como você constrói rapport com clientes?', category: 'relacionamento' },
    { id: 'comercial-6', question: 'Qual pergunta fecha mais vendas?', category: 'fechamento' },
    { id: 'comercial-7', question: 'Como você lida com "não" do cliente?', category: 'resiliência' },
    { id: 'comercial-8', question: 'Qual seu diferencial competitivo?', category: 'posicionamento' },
    { id: 'comercial-9', question: 'Como você acompanha pipeline?', category: 'gestão' },
    { id: 'comercial-10', question: 'Qual follow-up gerou resultado?', category: 'persistência' },
    { id: 'comercial-11', question: 'Como você identifica dores do cliente?', category: 'descoberta' },
    { id: 'comercial-12', question: 'Qual CRM você recomenda?', category: 'ferramenta' },
    { id: 'comercial-13', question: 'Como você lida com preço como objeção?', category: 'objeção' },
    { id: 'comercial-14', question: 'Qual estratégia de prospecção funciona?', category: 'prospecção' },
    { id: 'comercial-15', question: 'Como você prepara reuniões de venda?', category: 'preparação' },
    { id: 'comercial-16', question: 'Qual livro de vendas te marcou?', category: 'aprendizado' },
    { id: 'comercial-17', question: 'Como você faz upsell naturalmente?', category: 'expansão' },
    { id: 'comercial-18', question: 'Qual métrica você acompanha diariamente?', category: 'kpi' },
    { id: 'comercial-19', question: 'Como você celebra vitórias?', category: 'motivação' },
    { id: 'comercial-20', question: 'Qual script de ligação funciona?', category: 'script' },
    { id: 'comercial-21', question: 'Como você lida com decisores múltiplos?', category: 'complexidade' },
    { id: 'comercial-22', question: 'Qual técnica de fechamento prefere?', category: 'fechamento' },
    { id: 'comercial-23', question: 'Como você gera urgência genuína?', category: 'timing' },
    { id: 'comercial-24', question: 'Qual erro de vendas você evita?', category: 'experiência' },
    { id: 'comercial-25', question: 'Como você reativa clientes inativos?', category: 'reativação' },
    { id: 'comercial-26', question: 'Qual pergunta de qualificação é chave?', category: 'bant' },
    { id: 'comercial-27', question: 'Como você apresenta proposta de valor?', category: 'apresentação' },
    { id: 'comercial-28', question: 'Qual objeção você adora receber?', category: 'objeção' },
    { id: 'comercial-29', question: 'Como você mantém pipeline cheio?', category: 'prospecção' },
    { id: 'comercial-30', question: 'Qual incentivo te motiva mais?', category: 'motivação' },
    { id: 'comercial-31', question: 'Como você lida com rejeição?', category: 'mindset' },
    { id: 'comercial-32', question: 'Qual momento do ciclo prefere?', category: 'preferência' },
    { id: 'comercial-33', question: 'Como você escuta ativamente?', category: 'técnica' },
    { id: 'comercial-34', question: 'Qual recurso de vendas usa?', category: 'material' },
    { id: 'comercial-35', question: 'Como você negocia descontos?', category: 'negociação' },
    { id: 'comercial-36', question: 'Qual referência gerou mais negócios?', category: 'networking' },
    { id: 'comercial-37', question: 'Como você prioriza oportunidades?', category: 'gestão' },
    { id: 'comercial-38', question: 'Qual case de sucesso conta mais?', category: 'storytelling' },
    { id: 'comercial-39', question: 'Como você mantém relacionamento pós-venda?', category: 'retenção' },
    { id: 'comercial-40', question: 'Qual hábito diário não negocia?', category: 'rotina' },
    { id: 'comercial-41', question: 'Como você supera plateaus de performance?', category: 'crescimento' },
    { id: 'comercial-42', question: 'Qual canal de prospecção funciona?', category: 'canal' },
    { id: 'comercial-43', question: 'Como você lida com ciclos longos?', category: 'paciência' },
    { id: 'comercial-44', question: 'Qual mentor te inspirou?', category: 'inspiração' },
    { id: 'comercial-45', question: 'Como você treina sua pitch?', category: 'prática' },
    { id: 'comercial-46', question: 'Qual tecnologia ajuda suas vendas?', category: 'tech' },
    { id: 'comercial-47', question: 'Como você recupera deals perdidos?', category: 'resgate' },
    { id: 'comercial-48', question: 'Qual característica de top sellers você admira?', category: 'modelo' },
    { id: 'comercial-49', question: 'Como você equilibra quantidade e qualidade?', category: 'estratégia' },
    { id: 'comercial-50', question: 'Qual conselho daria ao você iniciante?', category: 'sabedoria' }
  ],

  'RH': [
    { id: 'rh-1', question: 'Como está o clima da equipe esta semana?', category: 'clima' },
    { id: 'rh-2', question: 'Que ação de bem-estar implementou?', category: 'bem-estar' },
    { id: 'rh-3', question: 'Como você identifica talentos internos?', category: 'talento' },
    { id: 'rh-4', question: 'Qual feedback mais te marcou?', category: 'feedback' },
    { id: 'rh-5', question: 'Como você promove cultura da empresa?', category: 'cultura' },
    { id: 'rh-6', question: 'Qual processo de RH melhorou?', category: 'processo' },
    { id: 'rh-7', question: 'Como você lida com conflitos?', category: 'mediação' },
    { id: 'rh-8', question: 'Qual iniciativa de inclusão implementou?', category: 'diversidade' },
    { id: 'rh-9', question: 'Como você retém talentos?', category: 'retenção' },
    { id: 'rh-10', question: 'Qual métrica de engajamento monitora?', category: 'engajamento' },
    { id: 'rh-11', question: 'Como você conduz entrevistas?', category: 'recrutamento' },
    { id: 'rh-12', question: 'Qual programa de desenvolvimento funciona?', category: 'treinamento' },
    { id: 'rh-13', question: 'Como você mede satisfação dos colaboradores?', category: 'pesquisa' },
    { id: 'rh-14', question: 'Qual ferramenta de RH você recomenda?', category: 'tecnologia' },
    { id: 'rh-15', question: 'Como você lida com turnover?', category: 'desafio' },
    { id: 'rh-16', question: 'Qual política de RH você criou?', category: 'política' },
    { id: 'rh-17', question: 'Como você promove diversidade?', category: 'inclusão' },
    { id: 'rh-18', question: 'Qual estratégia de onboarding usa?', category: 'integração' },
    { id: 'rh-19', question: 'Como você desenvolve lideranças?', category: 'liderança' },
    { id: 'rh-20', question: 'Qual desafio de pessoas enfrentou?', category: 'desafio' },
    { id: 'rh-21', question: 'Como você celebra conquistas da equipe?', category: 'reconhecimento' },
    { id: 'rh-22', question: 'Qual métrica de performance acompanha?', category: 'performance' },
    { id: 'rh-23', question: 'Como você estrutura feedbacks?', category: 'avaliação' },
    { id: 'rh-24', question: 'Qual benefício os colaboradores mais valorizam?', category: 'benefícios' },
    { id: 'rh-25', question: 'Como você lida com demissões?', category: 'desligamento' },
    { id: 'rh-26', question: 'Qual ação reduziu conflitos?', category: 'clima' },
    { id: 'rh-27', question: 'Como você atrai talentos?', category: 'employer-branding' },
    { id: 'rh-28', question: 'Qual treinamento teve mais impacto?', category: 'capacitação' },
    { id: 'rh-29', question: 'Como você mapeia sucessores?', category: 'sucessão' },
    { id: 'rh-30', question: 'Qual indicador de RH é crítico?', category: 'kpi' },
    { id: 'rh-31', question: 'Como você promove saúde mental?', category: 'saúde' },
    { id: 'rh-32', question: 'Qual erro de RH você evita?', category: 'aprendizado' },
    { id: 'rh-33', question: 'Como você equilibra rigidez e flexibilidade?', category: 'gestão' },
    { id: 'rh-34', question: 'Qual ritual de equipe funciona?', category: 'cultura' },
    { id: 'rh-35', question: 'Como você conduz PDIs?', category: 'desenvolvimento' },
    { id: 'rh-36', question: 'Qual política de trabalho remoto adotou?', category: 'flexibilidade' },
    { id: 'rh-37', question: 'Como você mede cultura organizacional?', category: 'cultura' },
    { id: 'rh-38', question: 'Qual estratégia de reconhecimento usa?', category: 'motivação' },
    { id: 'rh-39', question: 'Como você lida com baixo desempenho?', category: 'performance' },
    { id: 'rh-40', question: 'Qual parceria externa funciona?', category: 'networking' },
    { id: 'rh-41', question: 'Como você promove equilíbrio vida-trabalho?', category: 'bem-estar' },
    { id: 'rh-42', question: 'Qual competência comportamental valoriza?', category: 'soft-skills' },
    { id: 'rh-43', question: 'Como você estrutura plano de carreira?', category: 'carreira' },
    { id: 'rh-44', question: 'Qual transformação de RH liderou?', category: 'mudança' },
    { id: 'rh-45', question: 'Como você comunica mudanças organizacionais?', category: 'comunicação' },
    { id: 'rh-46', question: 'Qual book ou curso te inspirou?', category: 'aprendizado' },
    { id: 'rh-47', question: 'Como você previne burnout?', category: 'prevenção' },
    { id: 'rh-48', question: 'Qual valor da empresa você reforça mais?', category: 'valores' },
    { id: 'rh-49', question: 'Como você define sucesso em RH?', category: 'propósito' },
    { id: 'rh-50', question: 'Qual legado quer deixar na organização?', category: 'impacto' }
  ],

  'Financeiro': [
    { id: 'fin-1', question: 'Que oportunidade de economia identificou?', category: 'eficiência' },
    { id: 'fin-2', question: 'Como você prevê tendências financeiras?', category: 'previsão' },
    { id: 'fin-3', question: 'Qual análise foi mais impactante?', category: 'análise' },
    { id: 'fin-4', question: 'Como comunica finanças para não-financeiros?', category: 'comunicação' },
    { id: 'fin-5', question: 'Qual indicador financeiro monitora mais?', category: 'kpi' },
    { id: 'fin-6', question: 'Como você controla fluxo de caixa?', category: 'gestão' },
    { id: 'fin-7', question: 'Qual investimento recomendou?', category: 'investimento' },
    { id: 'fin-8', question: 'Como você negocia com fornecedores?', category: 'negociação' },
    { id: 'fin-9', question: 'Qual relatório gera mais valor?', category: 'reporting' },
    { id: 'fin-10', question: 'Como você automatiza processos?', category: 'automação' },
    { id: 'fin-11', question: 'Qual erro financeiro evita sempre?', category: 'controle' },
    { id: 'fin-12', question: 'Como você estrutura orçamento anual?', category: 'planejamento' },
    { id: 'fin-13', question: 'Qual ferramenta financeira usa?', category: 'tecnologia' },
    { id: 'fin-14', question: 'Como você identifica desvios de budget?', category: 'monitoramento' },
    { id: 'fin-15', question: 'Qual estratégia de cobrança funciona?', category: 'recebíveis' },
    { id: 'fin-16', question: 'Como você analisa viabilidade de projetos?', category: 'análise' },
    { id: 'fin-17', question: 'Qual métrica de liquidez prioriza?', category: 'liquidez' },
    { id: 'fin-18', question: 'Como você gerencia riscos financeiros?', category: 'risco' },
    { id: 'fin-19', question: 'Qual indicador de rentabilidade acompanha?', category: 'rentabilidade' },
    { id: 'fin-20', question: 'Como você otimiza estrutura de capital?', category: 'estrutura' },
    { id: 'fin-21', question: 'Qual decisão financeira foi mais difícil?', category: 'decisão' },
    { id: 'fin-22', question: 'Como você previne inadimplência?', category: 'crédito' },
    { id: 'fin-23', question: 'Qual estratégia tributária aplica?', category: 'tributos' },
    { id: 'fin-24', question: 'Como você calcula ROI de iniciativas?', category: 'retorno' },
    { id: 'fin-25', question: 'Qual processo financeiro simplificou?', category: 'eficiência' },
    { id: 'fin-26', question: 'Como você lida com sazonalidade?', category: 'planejamento' },
    { id: 'fin-27', question: 'Qual dashboard financeiro usa?', category: 'visualização' },
    { id: 'fin-28', question: 'Como você valida premissas de previsão?', category: 'validação' },
    { id: 'fin-29', question: 'Qual política de crédito estabeleceu?', category: 'política' },
    { id: 'fin-30', question: 'Como você mede saúde financeira?', category: 'diagnóstico' },
    { id: 'fin-31', question: 'Qual KPI considera subestimado?', category: 'indicador' },
    { id: 'fin-32', question: 'Como você prioriza investimentos?', category: 'alocação' },
    { id: 'fin-33', question: 'Qual análise de sensibilidade realiza?', category: 'cenários' },
    { id: 'fin-34', question: 'Como você gerencia capital de giro?', category: 'operacional' },
    { id: 'fin-35', question: 'Qual estratégia de hedge usa?', category: 'proteção' },
    { id: 'fin-36', question: 'Como você apresenta resultados à diretoria?', category: 'apresentação' },
    { id: 'fin-37', question: 'Qual erro de forecast você evita?', category: 'previsão' },
    { id: 'fin-38', question: 'Como você concilia contas rapidamente?', category: 'rotina' },
    { id: 'fin-39', question: 'Qual certificação financeira recomenda?', category: 'educação' },
    { id: 'fin-40', question: 'Como você mantém controles internos?', category: 'governança' },
    { id: 'fin-41', question: 'Qual software de BI financeiro usa?', category: 'analytics' },
    { id: 'fin-42', question: 'Como você negocia taxas bancárias?', category: 'negociação' },
    { id: 'fin-43', question: 'Qual estratégia de pricing ajudou a definir?', category: 'pricing' },
    { id: 'fin-44', question: 'Como você equilibra curto e longo prazo?', category: 'estratégia' },
    { id: 'fin-45', question: 'Qual mudança regulatória te impactou?', category: 'compliance' },
    { id: 'fin-46', question: 'Como você identifica fraudes?', category: 'auditoria' },
    { id: 'fin-47', question: 'Qual benchmark financeiro usa?', category: 'comparação' },
    { id: 'fin-48', question: 'Como você otimiza impostos legalmente?', category: 'planejamento' },
    { id: 'fin-49', question: 'Qual conselho daria a novos analistas?', category: 'mentoria' },
    { id: 'fin-50', question: 'Como você define sucesso financeiro?', category: 'objetivo' }
  ]
}

/**
 * Obtém quebra-gelos para uma área específica
 */
export function getIcebreakers(area: string): Icebreaker[] {
  return icebreakersByArea[area] || icebreakersByArea['Designer']
}

/**
 * Obtém um quebra-gelo aleatório para uma área, evitando os últimos N usados
 */
export function getRandomIcebreaker(area: string, recentIds: string[] = [], count: number = 30): Icebreaker {
  const icebreakers = getIcebreakers(area)
  const available = icebreakers.filter(ice => !recentIds.slice(-count).includes(ice.id))
  
  if (available.length === 0) {
    // Se todos foram usados, resetar e pegar qualquer um
    return icebreakers[Math.floor(Math.random() * icebreakers.length)]
  }
  
  return available[Math.floor(Math.random() * available.length)]
}

/**
 * Obtém quebra-gelo do dia baseado em data e área
 */
export function getDailyIcebreaker(area: string, date: Date = new Date()): Icebreaker {
  const icebreakers = getIcebreakers(area)
  // Usa o dia do ano como seed para ter sempre a mesma pergunta no mesmo dia
  const dayOfYear = Math.floor((date.getTime() - new Date(date.getFullYear(), 0, 0).getTime()) / 86400000)
  const index = dayOfYear % icebreakers.length
  return icebreakers[index]
}


